verbose: true
optimizeInput: false
optimizeOutput: false
identifiers:
  rename: true
  renameGlobals: true
stream:
  - name: Debugger Breakpoint Loop
    file: ./transformations/debuggerBreakpointLoop.js
    enabled: true
  - name: Declarations Reordering
    file: ./transformations/declarationsReordering.js
    enabled: true
    settings:
      deeperBlockChance: 0.33 # 33% chance to move declaration deeper one block in the current scope
  - name: Computed Member # transforms object.property to object['property']
    file: ./transformations/computedMember.js
    enabled: true
  - name: Number Obfuscation
    file: ./transformations/numberObfuscation.js
    enabled: true
    settings:
      chance: 1 # 100% of numbers obfuscated
  - name: Function Parameters Reordering
    file: ./transformations/functionParametersReordering.js
    enabled: true
  - name: Operator Outlining
    file: ./transformations/operatorOutlining.js
    enabled: true
    settings:
      unaryOperatorChance: 0.75 # ~75% of unary operators outlined
      assignmentOperatorChance: 0.75 # ~75% of assignment operators transformed to binary ( a +=1 transforms into a = a + 1)
      binaryOperatorChance: 0.75 # ~75% of binary operators outlined
  - name: Console Redefinition
    file: ./transformations/consoleRedefinition.js
    enabled: false
  - name: Literal Obfuscation
    file: ./transformations/literalObfuscation.js
    enabled: true
    settings:
      splitChance: 0.50 # ~50% of strings splitted
      arrayChance: 0.9 # ~90% of strings moved to array
      base64Chance: 0.25 # ~25% of strings encoded to base64
      unicodeChance: 1 # 100% of strings converted to unicode escape sequence
  - name: Expression Obfuscation
    file: ./transformations/expressionObfuscation.js
    enabled: true
    settings:
      booleanChance: 0.9 # 90% of booleans obfuscated
      undefinedChance: 0.9 # 90% of 'undefined' expression obfuscated
  - name: Function Definition Reordering
    file: ./transformations/functionDefinitionReordering.js
    enabled: true
  - name: Function Merging
    file: ./transformations/functionMerging.js
    enabled: true
  - name: Eval Outlining
    file: ./transformations/evalOutlining.js
    enabled: true
    settings:
      chance: 0.1 # ~10% of expressions outlined to eval
  - name: Code Encryption & Integrity
    file: ./transformations/codeEncryption.js
    enabled: true
    settings:
      chance: 0.1 # ~10% of blocks encrypted
