verbose: true
stream:
  - name: Computed Member
    file: ./transformations/computedMember.js
    enabled: true
  - name: Operator Outlining
    file: ./transformations/operatorOutlining.js
    enabled: true
    settings:
      unaryOperators: true
      assignmentOperators: true
      binaryOperators: true
  - name: Console Replacement
    file: ./transformations/consoleReplacement.js
    enabled: false
  - name: Literal Obfuscator
    file: ./transformations/literalObfuscator.js
    enabled: true
  - name: Unicode Literal
    file: ./transformations/unicodeLiteral.js
    enabled: true
