verbose: true
stream:
  - name: Computed Member # transforms object.property to object['property']
    file: ./transformations/computedMember.js
    enabled: true
  - name: Operator Outlining
    file: ./transformations/operatorOutlining.js
    enabled: true
    settings:
      unaryOperators: true
      assignmentOperators: true
      binaryOperators: true
  - name: Console Redefinition
    file: ./transformations/consoleRedefinition.js
    enabled: false
  - name: Expression Obfuscation
    file: ./transformations/expressionObfuscation.js
    enabled: true
    settings:
      booleanThreshold: 0.8 # 80% of booleans obfuscated
      undefinedThreshold: 0.8 # 80% of 'undefined' expression obfuscated
  - name: Number Obfuscation
    file: ./transformations/numberObfuscation.js
    enabled: true
    settings:
      threshold: 0.5 # 50% of numbers obfuscated
  - name: Literal Obfuscation
    file: ./transformations/literalObfuscation.js
    enabled: true
    settings:
      splitThreshold: 0.25 # ~25% of strings splitted
      arrayThreshold: 0.85 # ~85% of strings moved to array
      base64Threshold: 0.25 # ~25% of strings encoded to base64
  - name: Unicode Literal
    file: ./transformations/unicodeLiteral.js
    enabled: true
  - name: Function Arguments Reordering
    file: ./transformations/functionArgumentsReordering.js
    enabled: true
  - name: Function Definition Reordering
    file: ./transformations/functionDefinitionReordering.js
    enabled: true
  - name: Eval Outlining
    file: ./transformations/evalOutlining.js
    enabled: true
    settings:
      threshold: 0.1 # ~10% of expressions outlined to eval
