verbose: true
stream:
  - name: Computed Member
    file: ./transformations/computedMember.js
    enabled: true
  - name: Operator Outlining
    file: ./transformations/operatorOutlining.js
    enabled: true
    settings:
      unaryOperators: true
      assignmentOperators: true
      binaryOperators: true
  - name: Console Replacement
    file: ./transformations/consoleReplacement.js
    enabled: false
  - name: Literal Obfuscator
    file: ./transformations/literalObfuscator.js
    enabled: true
    settings:
      splitThreshold: 0.25 # ~25% of strings splitted
      arrayThreshold: 0.85 # ~85% of strings moved to array
      base64Threshold: 0.25 # ~25% of strings encoded to base64
  - name: Unicode Literal
    file: ./transformations/unicodeLiteral.js
    enabled: true
